### ISSUE TITLE
Decode fails for anonymous structures

### ISSUE THREAD

**Issue by prog8** [mitchellh/mapstructure#113] opened 2018-04-12 19:27 UTC
I tried to decode from map to a struct which has anonymous struct inside. This works on simple `json.Marshal` -> `json.Unmarshal` but it fails in `mapstructure`. 

```
package deserializer

import (
	"encoding/json"
	"testing"
	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

type A struct {
	Field1 int
}

type B struct {
	A
	Field2 int
}

func TestAnonymous(t *testing.T) {
	b := B{}
	b.Field1 = 1
	b.Field2 = 2

	outB1 := &B{}
	serialized, _ := json.Marshal(b)
	json.Unmarshal(serialized, outB1)

	assert.Equal(t, b.Field1, outB1.Field1)
	assert.Equal(t, b.Field2, outB1.Field2)

	rawMap := make(map[string]interface{})
	json.Unmarshal(serialized, &rawMap)

	outB2 := &B{}
	mapstructure.Decode(rawMap, outB2)

	assert.Equal(t, b.Field1, outB2.Field1)
	assert.Equal(t, b.Field2, outB2.Field2)
}
```

This line fails `	assert.Equal(t, b.Field1, outB2.Field1)`

**Comment by prog8** [comment] 2018-04-12 21:01
I realized I have to use `mapstructure:",squash"`. Should I close this issue?

**Comment by jschoedt** [comment] 2018-09-23 16:41
I think this should work without the tag as that would be the expected behavior IMO.

**Comment by j0hnwhyte** [comment] 2019-02-19 11:50
I get the same problem. Adding the tag would break encapsulation, is there a way to specify it in the `Decode` call? What it's doing now is to completely ignore type embedding.

**Comment by j0hnwhyte** [comment] 2019-02-19 11:55
Anyway, this seems a dupe of #130 #62 #19 for the anon structures, the point here should be if it's possible to avoid the `squash` tag altogether

**Comment by mitchellh** [comment] 2020-03-18 23:29
#168 just added an option to always squash. I can't change the default now due to backwards compatibility concerns.

**Closed by mitchellh** 2020-03-18 23:29 UTC
