### ISSUE TITLE
failed to decode config

### ISSUE THREAD

**Issue by daixiang0** [mitchellh/mapstructure#165] opened 2019-06-28 09:30 UTC
Use below code to reproduce:
```
package main

import (
	"fmt"
	"github.com/mitchellh/mapstructure"
)

type Config struct {
	ClientConfig  clientConfig   `yaml:"client,omitempty"`
	ClientConfigs []clientConfig `yaml:"clients,omitempty"`
}

type clientConfig struct {
	URL string `"yaml:url,omitempty"`
}

func main() {

	input := map[string]interface{}{
		"client": map[string]string{
			"url": "http://198.168.181.61:3100/api/prom/push",
		},
	}

	var result Config
	err := mapstructure.Decode(input, &result)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%#v", result)

}
```

output:
```
main.Config{ClientConfig:main.clientConfig{URL:""}, ClientConfigs:[]main.clientConfig(nil)}
```

**Comment by daixiang0** [comment] 2019-07-06 05:21
@mitchellh hi, mind have a look?

**Comment by daixiang0** [comment] 2019-08-26 02:50
@mitchellh any input?

**Comment by daixiang0** [comment] 2019-08-27 06:10
@mfridman thanks very much, still has a questtion, if i write in configfile:
```
clients:
  - url: http://localhost:3100/api/prom/push
```
Seems it still can not work as expect.

**Comment by daixiang0** [comment] 2019-08-27 11:07
I tried to do special with this one, but still failed:
```
1 error(s) decoding:\n\n* 'client.url' expected a map, got 'string'
```
My setting:
```
URL flagext.URLValue `yaml:"url,omitempty"`
```

**Comment by daixiang0** [comment] 2019-08-28 02:23
My hook:
```
func parseURL() mapstructure.DecodeHookFunc {
	return func(f reflect.Type, t reflect.Type, data interface{}) (interface{}, error) {
		// based on https://github.com/cortexproject/cortex/blob/master/pkg/util/flagext/url.go#L19-L35
		if f.Kind() != reflect.String || t.Kind() != reflect.Struct {
			return data, nil
		}

		dataVal := data.(string)
		if strings.Contains(dataVal, "http") {
			url, err := url.Parse(dataVal)
			if err != nil {
				return nil, err
			}
			return url, nil
		}

		return data, nil
	}
}
```

**Comment by daixiang0** [comment] 2019-09-18 01:44
@mfridman mind have a look?

**Comment by mitchellh** [comment] 2020-03-18 23:59
Closing since this doesn't appear to be a reproducible issue.

**Closed by mitchellh** 2020-03-18 23:59 UTC
